version: 2.1

orbs:
  cli: circleci/circleci-cli@0.1.8

jobs:
  test:
    executor: cli/default
    steps:
      - cli/install
      - cli/setup
      - checkout
      - run:
          name: validate
          command: |
            circleci orb validate orb.yml

  publish:
    executor: cli/default
    steps:
      - cli/install
      - cli/setup
      - checkout
      - run:
          name: publish
          command: |
            circleci orb publish orb.yml junpayment/golangci-lint@${CIRCLE_TAG}

workflows:
  version: 2
  test:
    jobs:
      - test:
          filters:
            tags:
              ignore: /.*/
  publish:
    jobs:
      - publish:
          filters:
            tags:
              only: /^.*$/
            branches:
              ignore: /.*/

