version: 2.1

orbs:
  golangci-lint: junpayment/golangci-lint@0.0.1

executors:
  go:
    docker:
      - image: golang

jobs:
  bar:
    executor:
      name: go
    steps:
      - checkout
      - golangci-lint/exec

workflows:
  version: 2
  foo:
    jobs:
      - bar
